### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by saschatimme** [saschatimme/HomotopyContinuation2.jl#27]
## Missing features compared to HC 1.4

- [ ] multi-homogeneous total degree homotopy
  - [ ] start solutions iterator
  - [ ] construct start system

- [ ] Result
  - [ ] Aggregate informations (finite, singular, excess-solutions)
  - [ ] Multiplicity computation / information
    
- [ ] Progress information
- [ ] solve
  - [ ] polyhedral
  - [ ] total degree
  - [ ] parameter homotopy
  - [ ] homotopy
  - [ ] many parameter
  - [ ] homogeneous input
- [ ] complexity calculator
  - [ ] mixed volume
  - [ ] bezout number
- [ ] Unique Points
- [ ] monodromy
  - [ ] automatically compute linear start pair
  - [ ] tracking
  - [ ] group actions
  - [ ] trace test
- [ ] Allow to set start parameters, target parameters in track
- [ ] parallelization
  - [ ] monodromy
  - [ ] path tracking
  - [ ] solve

## Misc
- [ ] automatically apply horner rewrite rule

## Compability to 1.4 / Old Workflow

- [ ] Avoid name clashes between DynamicPolynomials and ModelKit
- [ ] `@polyvar` support

### Linear / Affine spaces
- [x] Affine subspaces
- [x] Affine subspace homotopy
- [ ] Affine sliced system
- [ ] Linear subspaces
- [ ] Linear subspace homotopy
- [ ] Linear sliced system

### Misc
- [ ] automatically compute monodromy start pair using Newton
- [x] usable Newton's method
- [x] excess solution check
- [ ] progress: show compilation time
